bioformula/app/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import auth, home, user, organic, reservation, certificate

urlpatterns = [
    path('', home.index, name='index'),
    path('register', home.register, name='register'),
    path('validation/<str:id>', user.validation, name='validation'),
    path('profile/<str:id>', user.profile, name='profile'),
    path('organic', organic.index, name='organic'),
    path('fertilizer', organic.fertilizer, name='fertilizer'),
    path('fertilizer-details/<str:id>', organic.fertilizer_details, name='fertilizer-details'),
    path('post-fertilizer-feedback/<str:id>', organic.post_fertilizer_feedback, name='post-fertilizer-feedback'),
    path('fertilizer-conversion', organic.fertilizer_conversion, name='fertilizer-conversion'),
    path('pesticide', organic.pesticide, name='pesticide'),
    path('pesticide-details/<str:id>', organic.pesticide_details, name='pesticide-details'),
    path('post-pesticide-feedback/<str:id>', organic.post_pesticide_feedback, name='post-pesticide-feedback'),
    path('pesticide-conversion', organic.pesticide_conversion, name='pesticide-conversion'),
    path('reservations', reservation.index, name='reservations'),
    path('new-reservation', reservation.add, name='new-reservation'),
    path('admin-reservation', reservation.admin_reservation, name='admin-reservation'),
    path('reservation-details/<str:id>', reservation.reservation_details, name='reservation-details'),
    path('signin', auth.signin, name='signin'),
    path('signout', auth.signout, name='signout'),
    path('forgot-password', auth.forgot, name='forgot-password'),
    path('new-password/<str:id>', auth.new_password, name='new-password'),
    path('certificate', certificate.index, name='certificate'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bioformula/biofarmula/urls.py
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = 'BioFarmula'
admin.site.index_title = 'BioFarmula Admin'
admin.site.site_title = 'BioFarmula Information System'

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

bioformula/app/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from .models import *
from django.core.validators import RegexValidator

CS = [('SINGLE', 'SINGLE'), ('MARRIED', 'MARRIED'), ('WIDOW', 'WIDOW'), ('WIDOWER', 'WIDOWER'), ('SEPARATED', 'SEPARATED')]
GENDER = [('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('RATHER NOT SAY', 'RATHER NOT SAY')]
RATING = [(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')]
RESERVATION_STATUS = [('PENDING', 'PENDING'), ('RE-SCHEDULE', 'RE-SCHEDULE'), ('RESERVED', 'RESERVED'), ('CANCEL', 'CANCEL')]

alphanumeric_with_hyphen = RegexValidator(
    regex=r'^[a-zA-Z0-9- ]+$',
    message='This field can only contain letters, numbers, and hyphens.'
)

class RegisterForm(forms.Form):
    firstname = forms.CharField(max_length=150, label='First Name', validators=[alphanumeric_with_hyphen], widget=forms.TextInput(attrs={'class': 'form-control email-bt', 'placeholder': 'First Name'}))
    middlename = forms.CharField(max_length=150, label='Middle Name', validators=[alphanumeric_with_hyphen], required=False, widget=forms.TextInput(attrs={'class': 'form-control email-bt', 'placeholder': 'Middle Name'}))
    lastname = forms.CharField(max_length=150, label='Last Name', validators=[alphanumeric_with_hyphen], widget=forms.TextInput(attrs={'class': 'form-control email-bt', 'placeholder': 'Last Name'}))
    email = forms.EmailField(label='Email', required=True, widget=forms.EmailInput(attrs={'class': 'form-control email-bt', 'placeholder': 'Email'}))

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get('email').upper() if cleaned_data.get('email') is not None else ''
        if User.objects.filter(username=email).exists():
            raise ValidationError("Email Address already exist")
        if User.objects.filter(email=email).exists():
            raise ValidationError("Email Address already exist")
        return cleaned_data
    
class ValidationForm(forms.Form):
    firstname = forms.CharField(max_length=150, label='First Name', validators=[alphanumeric_with_hyphen], widget=forms.TextInput(attrs={'class': 'form-control'}))
    middlename = forms.CharField(max_length=150, label='Middle Name', validators=[alphanumeric_with_hyphen], required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    lastname = forms.CharField(max_length=150, label='Last Name', validators=[alphanumeric_with_hyphen], widget=forms.TextInput(attrs={'class': 'form-control'}))
    suffix = forms.CharField(max_length=150, label='Extension', validators=[alphanumeric_with_hyphen], required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label='Email', required=True, widget=forms.EmailInput(attrs={'class': 'form-control', 'readonly': 'readonly'}))
    civil_status = forms.ChoiceField(label='Civil Status', choices=CS, widget=forms.Select(attrs={'class': 'form-control'}))
    gender = forms.ChoiceField(label='Gender', choices=GENDER, widget=forms.Select(attrs={'class': 'form-control'}))
    occupation = forms.CharField(max_length=150, label='Occupation', required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    address = forms.CharField(max_length=250, label='Address', required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    # contact_no = forms.CharField(max_length=30, label='Contact No.', required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    contact_no = forms.RegexField( max_length=11, min_length=11, label='Contact No.', required=True, regex=r'^\d{11}$', error_messages={'invalid': 'Please enter a valid contact number consisting of exactly 11 digits. Letters or special characters are not allowed.', 'required': 'Contact number is required.', 'min_length': 'Contact number must be 11 digits long.', 'max_length': 'Contact number must be 11 digits long.', },widget=forms.TextInput(attrs={'class': 'form-control', 'maxlength': '11'}))
    password = forms.CharField(max_length=30, label='Password', required=True, widget=forms.PasswordInput(attrs={'class': 'form-control'}))

class ProfileForm(forms.Form):
    firstname = forms.CharField(max_length=150, label='First Name', validators=[alphanumeric_with_hyphen], widget=forms.TextInput(attrs={'class': 'form-control'}))
    middlename = forms.CharField(max_length=150, label='Middle Name', validators=[alphanumeric_with_hyphen], required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    lastname = forms.CharField(max_length=150, label='Last Name', validators=[alphanumeric_with_hyphen], widget=forms.TextInput(attrs={'class': 'form-control'}))
    suffix = forms.CharField(max_length=150, label='Extension', validators=[alphanumeric_with_hyphen], required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label='Email', required=True, widget=forms.EmailInput(attrs={'class': 'form-control', 'readonly': 'readonly'}))
    civil_status = forms.ChoiceField(label='Civil Status', choices=CS, widget=forms.Select(attrs={'class': 'form-control'}))
    gender = forms.ChoiceField(label='Gender', choices=GENDER, widget=forms.Select(attrs={'class': 'form-control'}))
    occupation = forms.CharField(max_length=150, label='Occupation', required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    address = forms.CharField(max_length=250, label='Address', required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    # contact_no = forms.CharField(max_length=30, label='Contact No.', required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    contact_no = forms.RegexField( max_length=11, min_length=11, label='Contact No.', required=True, regex=r'^\d{11}$', error_messages={'invalid': 'Please enter a valid contact number consisting of exactly 11 digits. Letters or special characters are not allowed.', 'required': 'Contact number is required.', 'min_length': 'Contact number must be 11 digits long.', 'max_length': 'Contact number must be 11 digits long.', },widget=forms.TextInput(attrs={'class': 'form-control', 'maxlength': '11'}))
    image = forms.ImageField(label='Profile Picture', required=False)

class SigninForm(forms.Form):
    email = forms.EmailField(label='Email', required=True, widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password = forms.CharField(max_length=30, label='Password', required=True, widget=forms.PasswordInput(attrs={'class': 'form-control'}))

class ForgotPasswordForm(forms.Form):
    email = forms.EmailField(label='Email', required=True, widget=forms.EmailInput(attrs={'class': 'form-control'}))

class NewPasswordForm(forms.Form):
    password = forms.CharField(label='New Password', required=True, widget=forms.PasswordInput(attrs={'class': 'form-control'}))

class FertilizerSearchForm(forms.Form):
    search = forms.ModelChoiceField(queryset=FertilizersIngredients.objects.filter(fertilizer__status=True),required=False, widget=forms.Select(attrs={'class': 'form-control select-basic-single col-12', 'onchange': 'submitFertilizerForm()'}))

class PesticideSearchForm(forms.Form):
    search = forms.ModelChoiceField(queryset=PesticideIngredients.objects.filter(pesticide__status=True), required=False, widget=forms.Select(attrs={'class': 'form-control select-basic-single col-12', 'onchange': 'submitPesticideForm()'}))

class ReservationForm(forms.Form):
    event_type = forms.CharField(label='Event Type', max_length=150, widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 4}))
    start = forms.DateField(label='Start Date', widget=forms.DateInput(attrs={'class': 'form-control datepicker'}))
    end = forms.DateField(label='End Date', widget=forms.DateInput(attrs={'class': 'form-control datepicker'}))
    duration = forms.CharField(label='Duration', widget=forms.TextInput(attrs={'class': 'form-control'}))

class ReservationDetailsForm(forms.Form):
    event_type = forms.CharField(label='Event Type', max_length=150, widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 4}))
    start = forms.DateField(label='Start Date', widget=forms.DateInput(attrs={'class': 'form-control datepicker'}))
    end = forms.DateField(label='End Date', widget=forms.DateInput(attrs={'class': 'form-control datepicker'}))
    duration = forms.CharField(label='Duration', widget=forms.TextInput(attrs={'class': 'form-control'}))
    notes = forms.CharField(label='Notes', widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 4}))
    status = forms.ChoiceField(label='Status', choices=RESERVATION_STATUS, widget=forms.Select())

class PesticideConversionForm(forms.ModelForm):
    uom_qty = forms.IntegerField(label='Pesticide Size', required=False, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    uom = forms.ChoiceField(label='Unit of Measurement', required=False, widget=forms.Select())
    land_qty = forms.IntegerField(label='Land Size', required=False, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    land = forms.ChoiceField(label='Unit of Measurement', required=False, widget=forms.Select())

    class Meta:
        model = PesticideConversion
        fields = ['uom_qty', 'uom', 'land_qty', 'land']

    def __init__(self, *args, **kwargs):
        super(PesticideConversionForm, self).__init__(*args, **kwargs)
        self.instance = kwargs.get('instance', None)
        self.fields['uom'].choices = [
            (p.uom.uom_id, p.uom.name) for p in PesticideConversion.objects.filter(pesticide_id=self.instance.pk)
        ]
        self.fields['land'].choices = [
            (p.land.land_id, p.land.name) for p in PesticideConversion.objects.filter(pesticide_id=self.instance.pk)
        ]

class FertilizerConversionForm(forms.ModelForm):
    uom_qty = forms.IntegerField(label='Fertilizer Size', required=False, widget=forms.NumberInput(attrs={'class': 'form-control'}))

bioformula/app/views/certificate.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib import messages
from django.contrib.auth.models import User, Group
from datetime import date, datetime, timedelta, timezone
from django.db import transaction
from django.contrib.sessions.models import Session
from django.core.paginator import Paginator
from ..forms import *
from ..models import *
from ..email import *
from django.db.models import Q

def index(request):
    page = 'Certificate'
    try:
        if request.session['group'] != 'Admin':
            return HttpResponseRedirect("/")
        if request.method == "POST":
                form = CertificateForm(request.POST)
                if form.is_valid():
                    name = form.cleaned_data['name']
                    email = form.cleaned_data['email']
                    inclusive_date = form.cleaned_data['inclusive_date']
                    details = form.cleaned_data['details']
                    signatory = form.cleaned_data['signatory']
                    send_certificate(name, email, inclusive_date, details, signatory)
                    messages.success(request, 'Certificate Sent')
                    return HttpResponseRedirect("/certificate")
                else:
                    messages.warning(request, form.errors)
        form = CertificateForm()
        return render(request, 'app/certificate.html', {'page': page, 'form': form})
    except Exception as e:
        messages.error(request, str(e))
        return HttpResponseRedirect("/certificate")

bioformula/app/templates/app/index.html
{% extends 'app/base.html' %}
{% load static %}
{% block products %}
<div class="services_section layout_padding">
    <div class="container">
       <h1 class="services_taital">Organic Products</h1>
       <div class="services_section_2 layout_padding">
          <div class="row">
             <div class="col-md-6">
               <a href="{% url 'fertilizer' %}#fertilizer">
                  <div class="image_main">
                     <img src="{% static 'app/images/org-fert.png' %}" class="image_2">
                     <!-- <h2 class="vegetable_text">Organic Fertilizers</h2> -->
                  </div>
                  <h2>Organic Fertilizers</h2>
               </a>
             </div>
             <div class="col-md-6">
               <a href="{% url 'pesticide' %}#pesticide">
                  <div class="image_main">
                     <img src="{% static 'app/images/org-pest.png' %}" class="image_2">
                     <!-- <h2 class="vegetable_text">Organic Pesticides</h2> -->
                  </div>
                  <h2>Organic Pesticides</h2>
               </a>
             </div>
          </div>
       </div>
    </div>
 </div>
{% endblock %}

{% block about %}
<div class="about_section layout_padding" style="background-color: #defde0;">
    <div class="container-fluid">
       <div class="row">
          <div class="col-md-6">
             <div class="about_main">
                <h1 class="about_taital">About Badang ni Ignacio</h1>
                <p class="about_text">Badang ni Ignacio is run by Christian Life Community (CLC) and is accredited by Agricultural Training Institute (ATI) as a learning site for agriculture. It is an 11-hectare farm engaging both in plants and animals and is complete with facilities to provide students all the trainings they need in agriculture.
                  To learn and adopt topics on agriculture and crop science, organic and sustainable farming, swine farming, poultry farming, making of organic fertilizers, crop protection and management. </p>
                <div class="readmore_bt"><a href="#">Read More</a></div>
             </div>
          </div>
          <div class="col-md-6 padding_0">
             <div class="image_7"><img src="{% static 'app/images/img-7.png' %}"></div>
          </div>
       </div>
    </div>
 </div>
{% endblock %}

{% block choose %}

{% endblock %}

{% block client %}

    <div class="contact_section layout_padding">
       <div class="container">
          <h1 class="contact_text">Register</h1>
       </div>
    </div>
    <div class="contact_section_2 layout_padding">
       <div class="container-fluid">
          <div class="row">
             <div class="col-md-6">
                <div class="mail_main">
                   <form id="registration-form" action="{% url 'register' %}" method="POST">
                    {%include 'app/messages.html'%}
                    {% csrf_token %}
                      <div class="form-group">
                        {{form.firstname}}
                      </div>
                      <div class="form-group">
                        {{form.middlename}}
                      </div>
                      <div class="form-group">
                        {{form.lastname}}
                      </div>
                      <div class="form-group">
                        {{form.email}}
                        {{form.email.errors}}
                      </div>
                   <div class="send_btn">
                      <div class="main_bt"><button class="btn btn-success btn-lg" type="submit">Register</button></div>
                   </div>
                    </form>
                </div>
             </div>
             <div class="col-md-6">
                <div><img src="{% static 'app/images/gate.png' %}" class="image_13"></div>
             </div>
          </div>
       </div>
    </div>
 </div>
{% endblock %}

bioformula/app/templates/app/messages.html
{%if messages%}
    {%for message in messages%}
    <div class="alert {{message.tags}} m-2 text-center" id="alert-msg" role="alert">{{message}}</div> 
    {%endfor%}
{%endif%}

bioformula/app/templates/app/new-password.html
{% extends 'app/base.html' %}
{% load static %}

{% block choose %}
<div class="choose_section layout_padding">
    <div class="container">
        <h1 class="choose_taital" id="forgot">New Password</h1>
        <form action="{% url 'new-password' id %}#forgot" method="POST">
            {%include 'app/messages.html'%}
            {% csrf_token %}
            <div class="form-group">
                <label for="{{form.password.id_for_label}}" class="col-sm-12 col-form-label">{{form.password.label}} {%if form.password.field.required%}<i style="color:red">*</i>{%endif%}</label>
                {{form.password}}
            </div>
            <button class="btn btn-danger" type="submit">Apply new password</button>
        </form>
    </div>
 </div>
{% endblock %}

bioformula/app/templates/app/organic.html
{% extends 'app/base.html' %}
{% load static %}
{% block products %}
<div class="services_section layout_padding">
    <div class="container">
       <h1 class="services_taital" id="organic">Organic Products</h1>
       <div class="services_section_2 layout_padding">
          <div class="row">
             <div class="col-md-6">
                <a href="{% url 'fertilizer' %}#fertilizer">
                    <div class="image_main">
                     <img src="{% static 'app/images/img-2.png' %}" class="image_2" 
                           style="transition: all 0.3s ease; cursor: pointer; box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);"
                           onmouseover="this.style.transform='scale(1.1)'; this.style.boxShadow='5px 5px 15px rgba(0, 0, 0, 0.3)';"
                           onmouseout="this.style.transform='scale(1)'; this.style.boxShadow='0 0 5px rgba(0, 0, 0, 0.1)';">

                       <!-- <img src="{% static 'app/images/img-2.png' %}" class="image_2"> -->
                       <!-- <h2 class="vegetable_text">Organic Fertilizers</h2> -->
                    </div>
                    <h2>Organic Fertilizers</h2>
                </a>
             </div>
             <div class="col-md-6">
                <a href="{% url 'pesticide' %}#pesticide">
                    <div class="image_main">
                       <img src="{% static 'app/images/img-3.png' %}" class="image_2">
                       <!-- <h2 class="vegetable_text">Organic Pesticides</h2> -->
                    </div>
                    <h2>Organic Pesticides</h2>
                 </a>
             </div>
          </div>
       </div>
    </div>
</div>
<br>
{% endblock %}

bioformula/app/templates/app/pesticide-details.html
{% extends 'app/base.html' %}
{% load static %}
{% block choose %}
<div class="choose_section layout_padding">
    <div class="container" id="fertilizer">
        {% if details.0.image %}
        <div class="container">
            <div class="col-md-12 px-0">
                <img src="{{details.0.image.url}}" class="img-fluid">
            </div>
        </div>
        {% endif %}
       <h1 class="choose_taital">{{details.0.name}}</h1>
        <p style="text-align: left; font-weight: 500;">Description</p>
        <div style="border: 1px solid #ccc; width: 100%; height: auto; margin-top: 0; padding-top: 0;">
        <p style="text-align: justify; font-weight: 400;">{{details.0.description}}</p>
        </div>
        <p style="text-align: left; font-weight: 500;">Materials</p>
        <div style="border: 1px solid #ccc; width: 100%; height: auto; margin-top: 0; padding-top: 0;">
            <ul class="col-12">
                {% for i in ing %}
                <li class="li-">{{i.description}}</li>
                {% endfor %}
            </ul>
        </div>
        <p style="text-align: left; font-weight: 500;">Procedures</p>
        <div style="border: 1px solid #ccc; width: 100%; height: auto; margin-top: 0; padding-top: 0;">
            <ol class="col-12">
                {% for i in proc %}
                <li class="li-">{{i.procedure}}</li>
                {% endfor %}
            </ol>
        </div>
        {% if source %}
        <p style="text-align: left; font-weight: 500;">Sources</p>
        <div style="border: 1px solid #ccc; width: 100%; height: auto; margin-top: 0; padding-top: 0;">
            <ul class="col-12">
                {% for i in source %}
                <li class="li-">{{i.source}} - <a href="{{i.link}}" target="_blank">{{i.link}}</a></li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        <hr>
        <form>
            <div class="container-fluid">
                <form action="#" method="POST">
                <div class="row">
                    <div class="col-md-6">
                        <label for="{{form.uom_qty.id_for_label}}" class="col-sm-12 col-form-label">{{form.uom_qty.label}} {%if form.uom_qty.field.required%}<i style="color:red">*</i>{%endif%}</label>
                        {{form.uom_qty}}
                    </div>
                    <div class="col-md-6 padding_0">
                        <label for="{{form.uom.id_for_label}}" class="col-sm-12 col-form-label">{{form.uom.label}} {%if form.uom.field.required%}<i style="color:red">*</i>{%endif%}</label>
                        {{form.uom}}
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <label for="{{form.land_qty.id_for_label}}" class="col-sm-12 col-form-label">{{form.land_qty.label}} {%if form.land_qty.field.required%}<i style="color:red">*</i>{%endif%}</label>
                        {{form.land_qty}}
                    </div>
                    <div class="col-md-6 padding_0">
                        <label for="{{form.land.id_for_label}}" class="col-sm-12 col-form-label">{{form.land.label}} {%if form.land.field.required%}<i style="color:red">*</i>{%endif%}</label>
                        {{form.land}}
                    </div>
                </div>
                </form>
            </div>
        </form>
    </div>
    <br><br><br>
    <div class="container">
        <div class="comment-section">
            <h2>Comments</h2>
            {%include 'app/messages.html'%}
            <!-- Comment Form -->
            {% if request.session.userid %}
            <div class="comment-form">
                <form action="{% url 'post-pesticide-feedback' id %}" method="POST">
                    {% csrf_token %}
                    <textarea placeholder="Write your comment here..." rows="4" name="feedback"></textarea>
        
                    <div class="rating">
                        <div class="stars">
                            <input type="radio" id="star5" name="rating" value="5">
                            <label for="star5">&#9733;</label>
                            <input type="radio" id="star4" name="rating" value="4">
                            <label for="star4">&#9733;</label>
                            <input type="radio" id="star3" name="rating" value="3">
                            <label for="star3">&#9733;</label>
                            <input type="radio" id="star2" name="rating" value="2">
                            <label for="star2">&#9733;</label>
                            <input type="radio" id="star1" name="rating" value="1">
                            <label for="star1">&#9733;</label>
                        </div>
                    </div>

                    <button type="submit">Post Comment</button>
                </form>
            </div>
            {% else %}
            <div class="comment-form">
                <p style="font-size: 12pt; text-align: center;"><a href="{% url 'signin' %}" style="color:green">Login</a> to post your comment</p>
            </div>
            {% endif %}
    
            <!-- Comments List -->
            <ul class="comments-list" id="comment">
                {% for i in feedback %}
                <li class="comment">
                    <div class="comment-author">
                        {% if i.image.url %}
                        <img src="{{i.image.url}}" alt="Profile Picture" class="comment-author-picture">
                        {% else %}
                        <img src="{{i.image}}" alt="Profile Picture" class="comment-author-picture">
                        {% endif %}
                        {{i.user.first_name}} {{i.user.last_name}}
                    </div>
                    <div class="comment-time">{{i.datetime_posted|date:'F d, Y h:i a'}}</div>
                    <div class="comment-text">{{i.feedback}}</div>
                    <div class="comment-rating">
                        {% if i.rating == 1 %}
                        <span class="stars">&#9733;</span>
                        {% elif i.rating == 2 %}
                        <span class="stars">&#9733;&#9733;</span>
                        {% elif i.rating == 3 %}
                        <span class="stars">&#9733;&#9733;&#9733;</span>
                        {% elif i.rating == 4 %}
                        <span class="stars">&#9733;&#9733;&#9733;&#9733;</span>
                        {% elif i.rating == 5 %}
                        <span class="stars">&#9733;&#9733;&#9733;&#9733;&#9733;</span>
                        {% endif %}
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
 </div>
{% endblock %}

{% block pesticide_script %}
<script>
   $("#id_uom_qty").on("change", function(){
      var uom_qty = $('#id_uom_qty').val()
      var uom = $("#id_uom").val()
      var land_qty = $("#id_land_qty").val()
      var land = $("#id_land").val()
      var define = "UOM"
      $.ajax({
         type: 'POST',
         url: '{% url "pesticide-conversion" %}',
         data: {
                'uom_qty'               : uom_qty,
                'uom'                   : uom,
                'land_qty'              : land_qty,
                'land'                  : land,
                'define'                : define,
                'id'                    : '{{id}}',
                'csrfmiddlewaretoken'   : '{{ csrf_token }}'
         },
         success: function(response) {
            if (response.status == 'success'){
                $("#id_land_qty").val(response.result)
            }else{
                alert("Error encountered")
                location.reload()
            }
         },
         error: function(xhr, status, error) {
               console.log(error)
         }
      });
   })

   $("#id_uom").on("change", function(){
      var uom_qty = $('#id_uom_qty').val()
      var uom = $("#id_uom").val()
      var land_qty = $("#id_land_qty").val()
      var land = $("#id_land").val()
      var define = "UOM"
      $.ajax({
         type: 'POST',
         url: '{% url "pesticide-conversion" %}',
         data: {
                'uom_qty'               : uom_qty,
                'uom'                   : uom,
                'land_qty'              : land_qty,
                'land'                  : land,
                'define'                : define,
                'id'                    : '{{id}}',
                'csrfmiddlewaretoken'   : '{{ csrf_token }}'
         },
         success: function(response) {
            if (response.status == 'success'){
                $("#id_land_qty").val(response.result)
            }else{
                alert("Error encountered")
                location.reload()
            }
         },
         error: function(xhr, status, error) {
               console.log(error)
         }
      });
   })

   $("#id_land_qty").on("change", function(){
      var uom_qty = $('#id_uom_qty').val()
      var uom = $("#id_uom").val()
      var land_qty = $("#id_land_qty").val()
      var land = $("#id_land").val()
      var define = "LAND"
      $.ajax({
         type: 'POST',
         url: '{% url "pesticide-conversion" %}',
         data: {
                'uom_qty'               : uom_qty,
                'uom'                   : uom,
                'land_qty'              : land_qty,
                'land'                  : land,
                'define'                : define,
                'id'                    : '{{id}}',
                'csrfmiddlewaretoken'   : '{{ csrf_token }}'
         },
         success: function(response) {
            if (response.status == 'success'){
                $("#id_uom_qty").val(response.result)
            }else{
                alert("Error encountered")
                location.reload()
            }
         },
         error: function(xhr, status, error) {
               console.log(error)
         }
      });
   })

   $("#id_land").on("change", function(){
      var uom_qty = $('#id_uom_qty').val()
      var uom = $("#id_uom").val()
      var land_qty = $("#id_land_qty").val()
      var land = $("#id_land").val()
      var define = "LAND"
      $.ajax({
         type: 'POST',
         url: '{% url "pesticide-conversion" %}',
         data: {
                'uom_qty'               : uom_qty,
                'uom'                   : uom,
                'land_qty'              : land_qty,
                'land'                  : land,
                'define'                : define,
                'id'                    : '{{id}}',
                'csrfmiddlewaretoken'   : '{{ csrf_token }}'
         },
         success: function(response) {
            if (response.status == 'success'){
                $("#id_uom_qty").val(response.result)
            }else{
                alert("Error encountered")
                location.reload()
            }
         },
         error: function(xhr, status, error) {
               console.log(error)
         }
      });
   })
</script>
{% endblock %}